### ISSUE TITLE
It's dead

### ISSUE THREAD

**Issue by David1544** [FourMan/4#25]
Problem: Project died
Proposed Solution: Revive it

**Comment by nv-vn** [comment]
idk i kinda gave up when fourguy stopped coming on the IRC and since he owns the repository im not really able to commit anything. @FourMan if you're out there msg me on IRC fam

**Comment by FourMan** [comment]
Will revive. nv-vn, I made you an admin of this project.

**Comment by nv-vn** [comment]
@FourMan mind getting on #🍀 ?

**Comment by David1544** [comment]
Yay

**Comment by correcthorsebatterystaple-sudo** [comment]
Rest in peace.

**Comment by nv-vn** [comment]
:(
